### ISSUE TITLE
assessing which categorical variable is significant?

### ISSUE THREAD

**Issue by Jigyasa3** [mrborges23/delta_statistic#5]
Hey @mrborges23 

Thank you for the delta_statistic code! 
From the code, a high value of "deltaA" suggests a phylogenetic signal. But is it possible to extract out information about which category is significant across the tree OR which category is driving the phylogenetic signal?

Thanks!

**Comment by mrborges23** [comment]
Dear @Jigyasa3, 
Thanks for your interest in our work!
The entropy is calculated across the categories, so all of them contributed to the measured phylogenetic signal. Thus, one cannot attributed phylogenetic signal to specific categories; but only for traits. 
Let me know if you have any other comments/question.
